// <auto-generated />
namespace eUniverzitet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inicijalna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inicijalna));
        
        string IMigrationMetadata.Id
        {
            get { return "202111281518594_Inicijalna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
